-- Menu item availability (sold out) + audit log

ALTER TABLE menu_items
  ADD COLUMN IF NOT EXISTS is_available boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS sold_out_at timestamptz DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS sold_out_reason text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS auto_reset_enabled boolean DEFAULT true;

UPDATE menu_items SET is_available = true WHERE is_available IS NULL;

CREATE TABLE IF NOT EXISTS availability_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  menu_item_id bigint NOT NULL REFERENCES menu_items(id) ON DELETE CASCADE,
  cafeteria_id bigint NOT NULL,
  changed_by text NOT NULL,
  previous_status boolean NOT NULL,
  new_status boolean NOT NULL,
  reason text,
  reset_type text DEFAULT 'manual' CHECK (reset_type IN ('manual', 'auto_midnight')),
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_availability_logs_cafeteria_created
  ON availability_logs (cafeteria_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_menu_items_cafeteria_available
  ON menu_items (cafeteria_id, is_available);

COMMENT ON COLUMN menu_items.is_available IS 'true = orderable, false = sold out';
COMMENT ON COLUMN menu_items.auto_reset_enabled IS 'When true, midnight job restores availability';
