-- Roles/Enum types if preferred, or just check constraints as they were in SQLite
-- Users table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT CHECK(role IN ('admin', 'student', 'cafeteria')) NOT NULL,
    contact TEXT
);

-- Cafeterias table
CREATE TABLE IF NOT EXISTS cafeterias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    location TEXT,
    contact TEXT,
    profile_picture TEXT
);

-- Orders table
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    cafeteria_id BIGINT NOT NULL REFERENCES cafeterias(id) ON DELETE CASCADE,
    total_amount REAL NOT NULL,
    status TEXT CHECK(status IN ('pending', 'processing', 'completed', 'cancelled')) DEFAULT 'pending',
    payment_method TEXT DEFAULT 'cash',
    payment_screenshot TEXT,
    payment_status TEXT CHECK(payment_status IN ('pending', 'approved', 'rejected')) DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Order Items table
CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    item_name TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    price REAL NOT NULL
);

-- Menu Categories table
CREATE TABLE IF NOT EXISTS menu_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cafeteria_id BIGINT NOT NULL REFERENCES cafeterias(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Menu Items table
CREATE TABLE IF NOT EXISTS menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cafeteria_id BIGINT NOT NULL REFERENCES cafeterias(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    price REAL NOT NULL,
    category TEXT CHECK(category IN ('Meals', 'Snacks', 'Drinks')) DEFAULT 'Meals',
    description TEXT,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Payment Info table (one row per cafeteria)
CREATE TABLE IF NOT EXISTS payment_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cafeteria_id BIGINT UNIQUE NOT NULL REFERENCES cafeterias(id) ON DELETE CASCADE,
    jazzcash_enabled SMALLINT DEFAULT 1,
    jazzcash_name TEXT,
    jazzcash_number TEXT,
    easypaisa_enabled SMALLINT DEFAULT 1,
    easypaisa_name TEXT,
    easypaisa_number TEXT,
    bank_name TEXT,
    bank_account TEXT,
    bank_instructions TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
