/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          colors: {
              "surface-container-high": "#28283a",
              "on-primary-container": "#5f1900",
              "surface-container-highest": "#333345",
              "on-surface": "#e3e0f8",
              "on-tertiary-container": "#003744",
              "surface": "#121222",
              "on-surface-variant": "#e1bfb5",
              "on-primary": "#5d1900",
              "surface-variant": "#333345",
              "surface-container-low": "#1a1a2b",
              "on-tertiary": "#003543",
              "on-primary-fixed-variant": "#832600",
              "on-secondary-container": "#fb9d7d",
              "primary-fixed": "#ffdbd0",
              "surface-container": "#1e1e2f",
              "surface-dim": "#121222",
              "tertiary-container": "#00a7cb",
              "inverse-surface": "#e3e0f8",
              "secondary": "#ffb59d",
              "surface-bright": "#38374a",
              "on-secondary": "#581d07",
              "inverse-primary": "#ab3500",
              "tertiary": "#59d5fb",
              "primary": "#ffb59d",
              "on-tertiary-fixed": "#001f28",
              "surface-container-lowest": "#0c0c1d",
              "tertiary-fixed-dim": "#59d5fb",
              "surface-tint": "#ffb59d",
              "on-secondary-fixed": "#390c00",
              "tertiary-fixed": "#b5ebff",
              "on-tertiary-fixed-variant": "#004e60",
              "error": "#ffb4ab",
              "primary-container": "#ff6b35",
              "on-error-container": "#ffdad6",
              "secondary-fixed": "#ffdbd0",
              "secondary-fixed-dim": "#ffb59d",
              "on-primary-fixed": "#390c00",
              "on-secondary-fixed-variant": "#76331b",
              "secondary-container": "#76331b",
              "on-background": "#e3e0f8",
              "inverse-on-surface": "#2f2f41",
              "error-container": "#93000a",
              "on-error": "#690005",
              "outline-variant": "#594139",
              "outline": "#a98a80",
              "background": "#121222",
              "primary-fixed-dim": "#ffb59d"
          },
          fontFamily: {
              "headline": ["Manrope", "sans-serif"],
              "body": ["Inter", "sans-serif"],
              "label": ["Inter", "sans-serif"]
          },
          borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
      },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
